export const MOCK_COMPLAINTS = [
  {
    id: 1,
    tracking_code: "CIV-2026-1001",
    title: "Severe Pothole on Main Arterial Road",
    description: "Deep hazardous pothole causing traffic slowdown and two-wheeler accidents.",
    category: "Pothole",
    priority: "CRITICAL",
    status: "IN_PROGRESS",
    latitude: 13.0827,
    longitude: 80.2707,
    address: "Anna Salai, Near Mount Road Flyover",
    zone_name: "Central Zone",
    created_at: "2026-07-28 09:15",
    citizen_name: "Priya Ramesh",
    citizen_phone: "+91 98765 43210",
    department: "Highways Department",
    assigned_officer: "Inspector K. Arumugam",
    field_worker: "Worker Team Alpha",
    estimated_hours: 12,
    image_url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600",
    after_image_url: null,
    ai_confidence: 96.5,
    is_genuine: true,
    qr_code_url: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=CIV-2026-1001",
    history: [
      { status: "SUBMITTED", timestamp: "2026-07-28 09:15", notes: "Complaint registered via Mobile App & AI verified", updated_by: "System AI" },
      { status: "OFFICER_NOTIFIED", timestamp: "2026-07-28 09:16", notes: "Routed to Highways Dept", updated_by: "Auto Router" },
      { status: "ACCEPTED", timestamp: "2026-07-28 10:00", notes: "Accepted by Officer K. Arumugam", updated_by: "Inspector K. Arumugam" },
      { status: "IN_PROGRESS", timestamp: "2026-07-28 11:30", notes: "Team Alpha dispatched to site with asphalt patch unit", updated_by: "Inspector K. Arumugam" }
    ]
  },
  {
    id: 2,
    tracking_code: "CIV-2026-1002",
    title: "Overflowing Garbage Dumpster near Park",
    description: "Garbage hasn't been collected for 4 days creating foul odor and health hazard.",
    category: "Garbage",
    priority: "MEDIUM",
    status: "SUBMITTED",
    latitude: 13.0850,
    longitude: 80.2750,
    address: "Block 4, Park Road, Zone 2",
    zone_name: "North Zone",
    created_at: "2026-07-28 11:40",
    citizen_name: "Senthil Nathan",
    citizen_phone: "+91 94441 12233",
    department: "Municipality",
    assigned_officer: null,
    field_worker: null,
    estimated_hours: 24,
    image_url: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600",
    after_image_url: null,
    ai_confidence: 95.8,
    is_genuine: true,
    qr_code_url: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=CIV-2026-1002",
    history: [
      { status: "SUBMITTED", timestamp: "2026-07-28 11:40", notes: "AI classified image as Garbage (95.8% confidence)", updated_by: "System AI" }
    ]
  },
  {
    id: 3,
    tracking_code: "CIV-2026-1003",
    title: "Water Pipeline Burst & Road Leakage",
    description: "High pressure clean drinking water leaking onto main road causing huge wastage.",
    category: "Water Leakage",
    priority: "HIGH",
    status: "ACCEPTED",
    latitude: 13.0780,
    longitude: 80.2650,
    address: "7th Cross Street, Lake View Area",
    zone_name: "East Zone",
    created_at: "2026-07-28 08:30",
    citizen_name: "Anand Kumar",
    citizen_phone: "+91 98400 99887",
    department: "Water Supply Board",
    assigned_officer: "Er. Suresh V",
    field_worker: null,
    estimated_hours: 16,
    image_url: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600",
    after_image_url: null,
    ai_confidence: 93.4,
    is_genuine: true,
    qr_code_url: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=CIV-2026-1003",
    history: [
      { status: "SUBMITTED", timestamp: "2026-07-28 08:30", notes: "Complaint logged by citizen", updated_by: "System AI" },
      { status: "ACCEPTED", timestamp: "2026-07-28 09:00", notes: "Pipe repair crew scheduled", updated_by: "Er. Suresh V" }
    ]
  },
  {
    id: 4,
    tracking_code: "CIV-2026-1004",
    title: "Non-functional Street Light Junction",
    description: "Entire street light line is off creating dark dangerous zone at night.",
    category: "Street Light",
    priority: "LOW",
    status: "WORK_COMPLETED",
    latitude: 13.0900,
    longitude: 80.2800,
    address: "Gandhi Road Junction, Zone 2",
    zone_name: "West Zone",
    created_at: "2026-07-27 14:20",
    citizen_name: "Kavitha R",
    citizen_phone: "+91 97900 11223",
    department: "Electricity Department",
    assigned_officer: "Er. Vikramaditya",
    field_worker: "Electrical Unit 4",
    estimated_hours: 24,
    image_url: "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=600",
    after_image_url: "https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=600",
    ai_confidence: 97.1,
    is_genuine: true,
    qr_code_url: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=CIV-2026-1004",
    history: [
      { status: "SUBMITTED", timestamp: "2026-07-27 14:20", notes: "Logged via mobile app", updated_by: "System AI" },
      { status: "WORK_COMPLETED", timestamp: "2026-07-28 10:15", notes: "Transformer fuse replaced and street LED fixture tested", updated_by: "Electrical Unit 4" }
    ]
  },
  {
    id: 5,
    tracking_code: "CIV-2026-1005",
    title: "Hazardous Open Sewage Drain",
    description: "Uncovered drain slab near school entrance. Very dangerous for children.",
    category: "Sewage Overflow",
    priority: "CRITICAL",
    status: "WORKER_ASSIGNED",
    latitude: 13.0810,
    longitude: 80.2720,
    address: "School Road, Block C",
    zone_name: "South Zone",
    created_at: "2026-07-28 07:45",
    citizen_name: "Rajesh Kannan",
    citizen_phone: "+91 99620 55443",
    department: "Water Supply Board",
    assigned_officer: "Er. Suresh V",
    field_worker: "Civil Concrete Team",
    estimated_hours: 8,
    image_url: "https://images.unsplash.com/photo-1509099836639-18ba1795216d?w=600",
    after_image_url: null,
    ai_confidence: 92.8,
    is_genuine: true,
    qr_code_url: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=CIV-2026-1005",
    history: [
      { status: "SUBMITTED", timestamp: "2026-07-28 07:45", notes: "High priority flag by AI", updated_by: "System AI" },
      { status: "WORKER_ASSIGNED", timestamp: "2026-07-28 08:15", notes: "Concrete cover replacement crew assigned", updated_by: "Er. Suresh V" }
    ]
  },
  {
    id: 6,
    tracking_code: "CIV-2026-1006",
    title: "Fallen Tree Branch Blocking Highway",
    description: "Large banyan tree branch broke in storm and blocked left lane.",
    category: "Fallen Tree",
    priority: "HIGH",
    status: "CITIZEN_VERIFIED",
    latitude: 13.0870,
    longitude: 80.2680,
    address: "National Highway Junction",
    zone_name: "North Zone",
    created_at: "2026-07-26 16:00",
    citizen_name: "Deepa Balan",
    citizen_phone: "+91 98410 77889",
    department: "Public Works Department",
    assigned_officer: "Er. Meena Sundaram",
    field_worker: "Forestry Clearance Unit",
    estimated_hours: 12,
    image_url: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600",
    after_image_url: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=600",
    ai_confidence: 98.2,
    is_genuine: true,
    qr_code_url: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=CIV-2026-1006",
    history: [
      { status: "SUBMITTED", timestamp: "2026-07-26 16:00", notes: "Reported by citizen", updated_by: "System AI" },
      { status: "CITIZEN_VERIFIED", timestamp: "2026-07-27 11:00", notes: "Citizen rated 5 Stars: 'Excellent work clearing highway'", updated_by: "Deepa Balan" }
    ]
  }
];

export const MOCK_DEPARTMENTS = [
  { id: 1, name: "Highways Department", code: "HIGHWAY", assigned: 48, resolved: 42, rate: 87.5, avg_time: 14.2 },
  { id: 2, name: "Municipality", code: "MUNI", assigned: 95, resolved: 88, rate: 92.6, avg_time: 21.0 },
  { id: 3, name: "Water Supply Board", code: "WATER", assigned: 64, resolved: 58, rate: 90.6, avg_time: 16.5 },
  { id: 4, name: "Electricity Department", code: "ELEC", assigned: 38, resolved: 36, rate: 94.7, avg_time: 11.8 },
  { id: 5, name: "Public Works Department", code: "PWD", assigned: 52, resolved: 47, rate: 90.3, avg_time: 18.0 }
];
