name: civiceye_citizen_app
description: "CivicEye AI-Powered Smart Public Complaint Management Citizen Mobile Application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.5.3
  camera: ^0.10.5+9
  location: ^5.0.3
  http: ^1.2.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
